apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-deployment
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: query
  template:
    metadata:
      labels:
        app: query
    spec:
      containers:
        - name: query
          image: blog/query:0.0.1

---
apiVersion: v1 
kind: Service
metadata:
  name: query-srv
spec:
  selector:
    app: query
  type: ClusterIP # default service is ClusterIP so it is optional to write here
  ports:
  - name: query
    protocol: TCP
    port: 4002
    targetPort: 4002
